### ISSUE TITLE
Consider recording last update datetime for pages?

### ISSUE THREAD

**Issue by patrickmj** [omeka/plugin-ExhibitBuilder#101]
An issue that comes up with Editorial is checking whether someone has edited/saved the page with a block (also a thing for any block, I think?). I'm looking for ways to check whether the page has been updated, and hence whether there's a potential problem with block ids.

I could potentially just record this page modified date among other info I'm storing about the editorial block and check that way, but wanted to raise it here as a potential feature.

A similar question is in this from the forums, about a workflow issue of tracking when something is published, rather than created: https://forum.omeka.org/t/publication-date/2673 .

**Comment by patrickmj** [comment]
Since Editorial would just be checking whether the page itself has been updated since it had been loaded, should all the checking that I had thought about putting in Editorial just be in ExhibitBuilder directly?

**Comment by zerocrates** [comment]
We've had reports of people being tripped up by this (two people working on a page at the same time, generally).

The trick is though, preventing the second save may help out a little in some data integrity stuff (I believe that's the Editorial issue) but doesn't necessarily help the users out all that much... We just shift the "your stuff got lost" from the first user to save to the second user. Though I suppose that's still better because it means at least the second user gets to see an error message telling them what went wrong, whereas in the current system they just save and think all is well even though they've silently clobbered the prior user's changes.

**Comment by zerocrates** [comment]
So I suppose, yes. I think it probably makes more sense, if we're going to do it, to do it in Exhibit Builder directly.

This same issue of competing saves comes up... basically everywhere in Omeka. I don't want to hold for it now, but it's probably worth seeing if we can do it in a way that's easily shifted over to the core and then applied all over the place.
