### ISSUE TITLE
Edit check sticks after page reload

### ISSUE THREAD

**Issue by patrickmj** [omeka/plugin-ExhibitBuilder#104]
With the new check on whether someone has edited a page, the warning message works as expected on the first submission. After that, though, changes are still rejected. I'd expect that after I get that message once I'd be able to redo my edits and continue. Only way to get back to being able to edit is to re-enter the URL -- reloading the page doesn't work.

**Comment by zerocrates** [comment]
Since it's a failure there's probably no redirect, so reloading is expected to fail (it's just saying to submit the same POST over again).

Resubmitting the form _should_ work though. The hidden input should be replaced with the new, correct modified date so it should allow you to proceed... It looks like something may be happening where the last modified date is actually updated on the record you have, it's just that it's not saved. So the date you have and print on the form is actually *more* recent than the real updated date.

Redirecting to the same page upon this kind of failure would be one pretty simple option that should work.

**Comment by patrickmj** [comment]
Yeah. the modified date that's put into the form isn't the actual modified date. It appears to be the current time in the form. Dunno why, though

**Comment by patrickmj** [comment]
Maybe since the `beforeSave` callback sets the modified time to current time, then because of the error it reloads the page with the same ExhibitPage object with the updated modified time, even though it hasn't been saved?

**Comment by zerocrates** [comment]
The likely reason is that the Timestamp mixin stuff on beforeSave probably still happens, so the date within the object is changed to the current date. The only part that gets stopped is the actual saving of the record to the database. Normally this would mean any changes to the object don't matter, but since you're taking that same record and passing it to the view, the newer, never-saved date is what's being used there.

**Comment by patrickmj** [comment]
Looks like we came to same conclusion while typing!

**Comment by patrickmj** [comment]
Quick fix seems to be putting this in `page-form.php` and use it instead. Good with this fix, or should I work on something less wonky?

```php

$databasePage = get_db()->getTable('ExhibitPage')->find($exhibit_page->id);

```

**Comment by patrickmj** [comment]
Alternative might be to reload the page in `editPageAction` if `$success` is false? If that actually works (testing cases now), that'd remove the database call on every load if that makes a difference.
